### ISSUE TITLE
pypi version has bug

### ISSUE THREAD

**Issue by falkben** [HumanBrainProject/neuroglancer-scripts#11]
Version on pypi (0.1.0) has a bug in which options are not passed correctly between functions (appears to have been fixed 5 months ago).  https://github.com/HumanBrainProject/neuroglancer-scripts/commit/f0e1e79ddd1b3ef772b6920399f732e9cd487df3

It would make it easier to use if you had an up to date version on pypi.  Thanks!

**Comment by ylep** [comment]
You are totally right, a new release was long overdue. Here it is: https://pypi.org/project/neuroglancer-scripts/0.2.0/
