### ISSUE TITLE
Not enough memory

### ISSUE THREAD

**Issue by stephen-zhouyang** [HumanBrainProject/neuroglancer-scripts#18]
When I produce precomputed files from png files, the program will take up a lot of memory. Is there any way to reduce memory consumption?

**Comment by ylep** [comment]
As currently implemented, the program needs to load enough slices at once to fill the whole thickness of a chunk, which may consume a significant amount of memory if each slice is very large.

You may try to decrease the chunk size in the direction of slice thickness, so less slices need to be loaded simultaneously. You could do so by adding a first scale to the `info` file with reduced chunk thickness, and discarding that first scale after the rest of the pyramid is computed.

We could think of a method that automates this process to fill only portions of a chunk at a time, and automatically discards the intermediate data. I have no plans to implement that feature myself though, but I would be happy to review a PR if some good soul wants to work on it :slightly_smiling_face:
