### ISSUE TITLE
[feature request ?] dropping support for py3.5 (ideally also py3.6 and py3.7)

### ISSUE THREAD

**Issue by xgui3783** [HumanBrainProject/neuroglancer-scripts#36]
Whilst writing a new feature (https://github.com/HumanBrainProject/neuroglancer-scripts/pull/35), I noticed that this package supports up to python 3.5

Whilst I was able to dance around a few restrictions, the lack of f-string support would mean rewriting a large chunk of code. Whilst they are mostly cosmetic, I do wonder if it is possible to remove py3.5 from supported list, since it is [well over 3 years past its EOL](https://devguide.python.org/versions/)

ping @ylep

**Comment by ylep** [comment]
Hi @xgui3783, no objection to dropping support for Python 3.5.

As for Python 3.6, it looks to be the highest version available in some still-supported distros (e.g. CentOS 7) so I'd prefer to keep support if that is not too much of a hassle.
