### ISSUE TITLE
flat files not created with '--flat' option using slices-to-precomputed command

### ISSUE THREAD

**Issue by falkben** [HumanBrainProject/neuroglancer-scripts#7]
When using the `slices-to-precomputed` command (example command below) I get a directory structure of files instead of a flat file structure.

`slices-to-precomputed slices output --flat` where slices and output are both directories.

Running `compute-scales` outputs the files in a flat structure without any problems.

Directory tree of output:
[tree.txt](https://github.com/HumanBrainProject/neuroglancer-scripts/files/2014651/tree.txt)

**Comment by falkben** [comment]
I believe the problem is on the following line:
https://github.com/HumanBrainProject/neuroglancer-scripts/blob/master/src/neuroglancer_scripts/scripts/slices_to_precomputed.py#L229

Options is always being passed as an empty dictionary when it should be passed `options`.

**Comment by ylep** [comment]
That was it, thanks for reporting!
